### ISSUE TITLE
the trait `Sum` is not implemented for `Vector<f64, 2_usize>`

### ISSUE THREAD

**Issue by burbokop** [agerasev/vecmat-rs#2]
It would be great to have std::iter::Sum implementation for Vector, Matrix and Complex

**Comment by agerasev** [comment]
Done :slightly_smiling_face: https://github.com/agerasev/vecmat-rs/commit/35b010cb5e60494958cbc6a3f1fdfed1205841c4
Do I understand correctly that this is what you asked for?
